// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoZ11_aEydfVkA-jWSxJ4J5O5ZldSNvF0',
    appId: '1:105725161586:web:f7093d60b9aad58d2612eb',
    messagingSenderId: '105725161586',
    projectId: 'chat-app-5ecb2',
    authDomain: 'chat-app-5ecb2.firebaseapp.com',
    storageBucket: 'chat-app-5ecb2.appspot.com',
    measurementId: 'G-7KG8EV9HXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdFHed7tQVmt16aW52uQX-Tggw2sYHlmI',
    appId: '1:105725161586:android:b90b4aa3688389f92612eb',
    messagingSenderId: '105725161586',
    projectId: 'chat-app-5ecb2',
    storageBucket: 'chat-app-5ecb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM_PlUXHBeqKeciXXd3AwgtCLitE8oOmU',
    appId: '1:105725161586:ios:697d1e73057e5dca2612eb',
    messagingSenderId: '105725161586',
    projectId: 'chat-app-5ecb2',
    storageBucket: 'chat-app-5ecb2.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM_PlUXHBeqKeciXXd3AwgtCLitE8oOmU',
    appId: '1:105725161586:ios:697d1e73057e5dca2612eb',
    messagingSenderId: '105725161586',
    projectId: 'chat-app-5ecb2',
    storageBucket: 'chat-app-5ecb2.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
